---
apiVersion: v1
kind: Service
metadata:
  name: mutatepodimages
  labels:
    app: mutatepodimages
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: mutatepodimages

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutatepodimages
  labels:
    app: mutatepodimages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutatepodimages
  template:
    metadata:
      name: mutatepodimages
      labels:
        app: mutatepodimages
    spec:
      containers:
        - name: mutator
          image: docker-local.art.aliocp.test.com/openshift3/k8s-mutate-webhook:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 64Mi

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutatepodimages
  labels:
    app: mutatepodimages
webhooks:
  - name: mutatepodimages.default.svc.cluster.local
    clientConfig:
      caBundle: ${caBundle}
      service:
        name: mutatepodimages
        namespace: default
        path: "/mutate"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Ignore
    namespaceSelector:
      matchLabels:
        mutatepodimages: enabled
