---
apiVersion: v1
kind: Pod
metadata:
  name: c7m
  labels:
    name: c7m
spec:
  containers:
  - name: c7m
    image: docker-dev-local.art.opsocp.test.com/demo/msc:0.0.1
    command:
      - /bin/bash
    args:
      - -c
      - trap "exit" TERM; while :; do sleep 1; done
